#!/usr/bin/env bash

# Bash script for retrieving subdomain details.

function get_single_subdomain_details {
    dig "${subdomain}.$domain" | grep -A1 'ANSWER SECTION:' | \
    awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", subdomain, $4, $5}' subdomain="${subdomain}"
}

function get_all_default_subdomain_details {
    default_subdomains=("www" "lb-01" "web-01" "web-02")

    for sub in "${default_subdomains[@]}";
    do
        dig "${sub}.$domain" | grep -A1 'ANSWER SECTION:' | \
        awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", sub, $4, $5}' sub="${sub}"
    done
}

if [ $# -lt 1 ]
then
    echo "Please provide a domain name."
elif [ $# -eq 1 ]
then
    domain="$1"
    get_all_default_subdomain_details "$domain"
else
    domain="$1"
    subdomain="$2"
    get_single_subdomain_details "$domain" "$subdomain"
fi
