#!/bin/bash

#1. Update the package repositories
#2. Install Nginx if it's not already installed
#3. Add custom response header to Nginx configuration
#4. Test Nginx configuration for syntax errors
# 5 & 6. Restart Nginx to apply changes

sudo apt-get -y update
sudo apt-get -y install nginx

header_line="add_header X-Served-By \$hostname;"
sudo sed -i "11i\\$header_line" /etc/nginx/nginx.conf
sudo nginx -t

sudo systemctl restart nginx
echo "Nginx has been configured with the custom X-Served-By header."
