#!/bin/bash
# Update the package repositories


sudo apt-get -y update
sudo apt-get -y install nginx
new_location='\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}'
error_line='\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}'
sudo sed -i "/server_name _;/ a \ $new_location" /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/a \ $error_line" /etc/nginx/sites-enabled/default
header_line="add_header X-Served-By \$hostname;"
sudo sed -i "11i\\$header_line" /etc/nginx/nginx.conf
sudo nginx -t
sudo systemctl restart nginx
echo "Nginx has been configured with the custom X-Served-By header."
