#!/usr/bin/env bash
# Installs and sets up HAProxy

# Install software-properties-common for add-apt-repository
apt-get install -y software-properties-common

# Add HAProxy repository (1.8 version)
add-apt-repository -y ppa:vbernat/haproxy-1.8

# Update the package repository
apt-get -y update

# Install HAProxy version 1.8
apt-get install -y haproxy=1.8.*

# Enable HAProxy service
echo "ENABLED=1" > /etc/default/haproxy

# Configure HAProxy to listen to web-01 and web-02 servers
echo "
listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 242358-web-01 100.25.180.249 check
   server 242358-web-02 54.196.30.13 check
" >> /etc/haproxy/haproxy.cfg

# Start the HAProxy service
service haproxy start