#!/usr/bin/env bash
#The display of listening ports

echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"

netstat -tuln | awk '$6 == "LISTEN" {printf "%-5s %-7s %-7s %-23s %-23s %s\n", $1, $2, $3, $4, $5, $NF}'

