#!/usr/bin/env bash
#make your fix short and sweet.

if ! pgrep nginx &> /dev/null; then
    sudo apt-get update
    sudo apt-get install -y nginx
fi

if ! pgrep nginx &> /dev/null; then
    sudo systemctl start nginx
fi

sudo sed -i '/listen 80;/s/#*//' /etc/nginx/sites-available/default
sudo systemctl reload nginx
