#!/usr/bin/env bash
#Task 5 we stop the other

# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -n "$pid" ]; then
    # Stop the process
    kill "$pid"
    echo "Terminated"
else
    echo "Process not found"
fi
