#!/usr/bin/env bash
#Task 6 stop me if you can

# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "7-highlander")

# Check if the process is running
if [ -n "$pid" ]; then
    # Send a termination signal to the process
    pkill -P "$pid"
else
    echo "Process not found"
fi

