#!/usr/bin/env bash
# This is the 10 times script

count=10

# Initialize counter
i=1

# Loop while counter is less than or equal to 10
while [ $i -le $count ]
do
  if [ $i -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi

  i=$((i+1))
done
