#!/usr/bin/env bash
#Task 7 Task time

# Initialize variables
hour=0
minute=1

# Loop while hour is less than or equal to 12 and minute is less than or equal to 59
while [ $hour -le 12 ]
do
  echo "Hour: $hour"

  # Loop while minute is less than or equal to 59
  while [ $minute -le 59 ]
  do
    echo $minute
    minute=$((minute+1))
  done

  minute=0
  hour=$((hour+1))
done | head -n 70
