#!/usr/bin/env bash
#The task 8

# Loop through each file in the current directory
for file in *; do
  # Check if the file is not hidden and is a regular file
  if [[ ! -f "$file" || "$file" == .* ]]; then
    continue
  fi

  # Extract the part of the name after the first dash
  filename=$(echo "$file" | cut -d '-' -f 2-)

  # Display the modified filename
  echo "$filename"
done
