#!/usr/bin/env bash
#turning root user from default and make default be nginx
# Ensure the script is run as root
if [ "$EUID" -ne 0 ]; then
  echo "This script must be run as root."
  exit 1
fi

# Define the desired username and port
nginx_user="nginx"
nginx_port="8080"

# Update Nginx configuration to use nginx user and desired port
sed -i "s/#user www-data/user $nginx_user/" /etc/nginx/nginx.conf
sed -i "s/listen 80;/listen $nginx_port;/g" /etc/nginx/sites-available/default

# Change permissions on nginx.conf
chmod 644 /etc/nginx/nginx.conf

# Stop Apache2 if it's running
if systemctl is-active --quiet apache2; then
  systemctl stop apache2
fi

# Start Nginx with the desired user
sudo -u $nginx_user service nginx start
